### ISSUE TITLE
Research - Google Api

### ISSUE THREAD

**Issue by treilly94** [scratch-map/scratch-map#1]

**Comment by emilioward** [comment]
@dcdarrell9 @treilly94 @srussell91 @KayleighB94 

I've used Google Maps API before at university i know that first we are going to need an API key from Google before we can integrate it into our application this is quite easy if we follow google's instructions (https://developers.google.com/maps/documentation/javascript/get-api-key) 

We'll just have to agree who's google profile will be tied to the API key unless we just create a generic account, call it (Ex QA devs) :laughing: that way we wont have to worry about someone deleting their google account one day. 

That site also gives you the html etc to setup a map straight onto your site under the tutorials section on the left hand side.

**Comment by dcdarrell9** [comment]
Decent. I was looking the my Google Analytics account earlier and noticed I was still linked with Andrew 😆 

How does it work with other languages? Should be simple for JS/React, but can we make requests from any language? And if we want to store certain bits of info/data?

How would it work if the maps api is down? Or there's no signal/data/location, how does it handle that? Or do we need to handle it?

How does the map come back to us? Can we change it up? I'm not a fan of just having a standard square google map box, I'd like it to be more like google earth where it's a full screen drag page and what not. But that's probably all further away anyway 🤷‍♂

**Comment by treilly94** [comment]
I've used the maps API for one of my django projects. It was pretty easy and I feel like we'd be able to make it work for most languages.
I've also got a API key that we could use for development
