### ISSUE TITLE
Review - Project Columns

### ISSUE THREAD

**Issue by dcdarrell9** [scratch-map/scratch-map#14]
**Describe the solution you'd like**
- Each of the columns in the project should have a note at the top describing it

**Describe alternatives you've considered**
- Is it worth having them?

**Additional context**
- A basic 'definition of done' and 'definition of ready' to be done first
- Linked to https://github.com/dcdarrell9/scratch-map/issues/13

**Comment by KayleighB94** [comment]
Colum description ideas:

To Do:
Speaks for itself

Ready to Work:
Work that is ready to be picked up that is clear what the objective is

In Progress:
1 ticket per person

Review Process:
Should be peer viewed by at least one 1 person, this peer viewed should check functionality, code quality, tests, documentation (if needed)

Definition of Done:
Met all the criteria all on the ticket, all test pass



For ready to deploy is that just for code changes and are we doing gitflow, as if yes to both this coloumn could be before done. Then it goes onto a release branch and moved into ready to deploy, then once release branch is tagged and moved, all the tickets then move into done. This would only apply to code tickets not exploration tickets though

**Comment by KayleighB94** [comment]
Alos instead of column descriptions, is it worth adding it all to the Contributing Guideline md file

**Comment by KayleighB94** [comment]
Sorry I realised I should of tagged people @treilly94 @dcdarrell9 @emilioward @srussell91
