### ISSUE TITLE
Research - CI/CD Tooling

### ISSUE THREAD

**Issue by treilly94** [scratch-map/scratch-map#4]
**Describe the solution you'd like**
Find appropiate CI/CD tools for this project.
This will include tools for pipelining but also things like static code analysis and code coverage.

**Describe alternatives you've considered**

**Additional context**

**Comment by treilly94** [comment]
Travis would be my default for a pipeline tool unless anyone knows of anything more appropiate

**Comment by treilly94** [comment]
Google has a tool called lighthouse for testing the quality of web pages.
https://developers.google.com/web/tools/lighthouse/
Could be worth looking at

**Comment by treilly94** [comment]
Some popular free options for pipelining are:

- https://travis-ci.org/
- https://about.gitlab.com/product/continuous-integration/
- https://circleci.com/pricing/

Personally I'd probably go for travis. The main downside to travis is the cost If we were going to go private. However if we were to go private it might be better to fork the repo and create a separate pipeline, possibly with GitlabCI.

If we keep all the logic in a build tool changing CI tools should be straightforward.

**Comment by emilioward** [comment]
Me & @dcdarrell9 are already familiar with travis and seemed to serve us well in our work. I really liked it checking each pr we submitted and checking against the unit tests. Although it used to time out against our BDD tests because there were so many! But i'd recommend it

**Comment by treilly94** [comment]
Yep, I'm a fan of travis. It seems like the obvious choice for me when using public github. 
But if its on a private repo its like $69/month. I think gitlabci is free on private repos.

https://travis-ci.com/plans
https://about.gitlab.com/pricing/

**Comment by emilioward** [comment]
Do we need to even go private? If we stay public then it's something we can show off on our CV's etc

**Comment by treilly94** [comment]
dont think we need to, but its nice to have the option.
Personally if we did go private I'd like to keep the open source version open source. Then fork it and make a private version with some closed source features

**Comment by dcdarrell9** [comment]
I'd consider looking at Concourse and Circle CI too, they're both similar, and chances are they'll end up doing the same things. After doing a bit of work with Jenkins I've started to like it, especially if you get the right plugins and what not, works pretty well. Spinnaker worth looking at as well

**Comment by treilly94** [comment]
How about to get things moving we use github actions? and try to keep as much of the logic as possible in the makefile to allow for easy transfer to another tool if we ever need?

**Comment by dcdarrell9** [comment]
Yeah, agreed. Let's go for a few github actions and Makefiles, we can swap over from there if needed. I'll leave this issue open until we actually add some actions / docs
